task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 10
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /media/ubuntu/7C48D20948D1C1D6/aproject/DEIM/dataset/VisDrone2019-DET-train/images
    ann_file: /media/ubuntu/7C48D20948D1C1D6/aproject/DEIM/dataset/VisDrone2019-DET-train/VisDrone2019-DET_train_coco.json
#    img_folder:  /media/ubuntu/B2529C30529BF777/Aproject/DATA/train2017
#    ann_file: /media/ubuntu/B2529C30529BF777/Aproject/RT-DETR-main/rtdetr_pytorch/configs/dataset/coco/labels/instances_train2017.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True 
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder:  /media/ubuntu/7C48D20948D1C1D6/aproject/DEIM/dataset/VisDrone2019-DET-test-dev/images
    ann_file: /media/ubuntu/7C48D20948D1C1D6/aproject/DEIM/dataset/VisDrone2019-DET-test-dev/VisDrone2019-DET_test_coco.json
#    img_folder: /media/ubuntu/7C48D20948D1C1D6/aproject/DEIM/dataset/VisDrone2019-DET-val/images
#    ann_file: /media/ubuntu/7C48D20948D1C1D6/aproject/DEIM/dataset/VisDrone2019-DET-val/VisDrone2019-DET_val_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 4
  drop_last: False
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction